fix: correct liana dotplot filterby parameter to filter_fun (#403)
* fix: correct liana dotplot filterby parameter to filter_fun

The liana.plotting.dotplot() function uses 'filter_fun' parameter (a callable)
instead of separate 'filterby' and 'filter_lambda' parameters.

Fixes TypeError: dotplot() got an unexpected keyword argument 'filterby'

* remove outcommented code

Signed-off-by: Lukas Heumos <lukas.heumos@posteo.net>

---------

Signed-off-by: Lukas Heumos <lukas.heumos@posteo.net>
Co-authored-by: Lukas Heumos <lukas.heumos@posteo.net>